### ISSUE TITLE
Manet Manager can't start ad-hoc mode

### ISSUE THREAD

**Issue by daviddoria** [monk-dot/SPAN#1]
I installed the Nexus 7 kernel, and then installed Manet Manager. When I click the big symbol to "start ad-hoc mode", a "Please wait while starting" dialog appears for about a half second, but then the symbol does not turn green and it says "Ad-hoc mode is not running". Any idea why it would not work after installing the modified kernel?

Thanks,

David

**Comment by jrobble** [comment]
David,

Is your device rooted?

Do you have the Wi-Fi-only or 3G Nexus 7? Also, the kernel is for the old
Nexus 7, not the new one.
- Jeff

**Comment by daviddoria** [comment]
Jeff,

The device is rooted (via ClockworkMod). It is the Wi-fi only Nexus 7 ME370T (2012).

David

**Comment by jrobble** [comment]
"adb shell" in as root and run the following command:
/data/data/org.span/bin/adhoc start 1

What output do you get?

**Comment by daviddoria** [comment]
Jeff,

Very sorry - apparently the device was not rooted. There was a prompt at one point that said "root device?" to which I answered yes, but apparently that was not the same thing as installing the SuperSU zip. All seems to be will now, sorry for the noise!
